Bug fix: Remove JS map from bookmarks view
geoblacklight/geoblacklight pull request #1008
Opened 2021-02-17 20:37 UTC by ewlarson

Make the GBL leaflet map selector more specific to prevent the map from rendering on the bookmarks view.

Fixes #246

2021-02-17 20:45 UTC, mejackreed requested changes
I wonder if we could/should tackle this issue a different way?

I say this as I would consider the map view of bookmarks a feature and removing this functionality would be a breaking change.

Would it be possible to instead know the context and pass an attribute through that could disable the map from displaying this?

2021-02-17 21:46 UTC, ewlarson commented
Hmmm... I thought we were leaning toward removing the bookmarks map altogether, as its current behavior is extremely unexpected. Did this work correctly in the past?

To have the map pan/zoom search work, bookmarks would need to be searchable. Or, are we talking about removing the geosearch functionality of the map?

2021-02-17 22:35 UTC, mejackreed commented
I'm talking specifically about removing the ability for the map to searchable in the context of the `BookmarksController`

2021-02-19 15:48 UTC, ewlarson commented
Closing. After discussion, I'll try another path.

2021-02-19 15:48 UTC, closed without merging