Combine download and export cards into dropdown button
geoblacklight/geoblacklight pull request #1194
Opened 2022-02-23 18:03 UTC by thanyabegum

Closes #1131

2022-02-23 19:07 UTC, tpendragon commented
@thanyabegum Can you add a screenshot to this PR when you get a chance?

2022-02-23 19:11 UTC, thanyabegum commented
> @thanyabegum Can you add a screenshot to this PR when you get a chance?

Will do!

2022-02-23 22:41 UTC, eliotjordan commented
I really like combining the downloads into a single place. It looks great _except_ in places where there is  "Derived Datasets" / related content section. Instead of dropdown, I wonder if this should be a an accordion panel. I suppose the drop down could be positioned last, I just worry about it getting lost in the page.

2022-02-23 23:10 UTC, karenmajewicz commented
Have we considered moving the Related Items widgets to the bottom of the metadata? Here is how the Big Ten is doing it example: https://geo.btaa.org/catalog/675283de1b4c429387bccc06655f9cee_1 We might not want default GBL to look exactly like that, but it does free up real estate in the right hand column.

2022-02-24 00:02 UTC, hackartisan commented
@eliotjordan we could try it as an accordion. I see what you mean about the content overlapping. We might still want to style it like a button, to make it a matched pair with the web services button.

2022-02-24 16:49 UTC, hackartisan commented on app/views/catalog/_downloads_dropdown.html.erb
> +    <%= download_link_generated(type.first, document) %>
I think we want this to keep the translation behavior that was previously in the helper method `download_generated_body`

2022-02-24 17:26 UTC, hackartisan commented
Here are some screenshots of the accordion / collapse implementation: 
![Screen Shot 2022-02-24 at 12 02 25 PM](https://user-images.githubusercontent.com/845363/155575826-8be38eac-3e0d-47b7-9371-d44c56a658b5.png)
![Screen Shot 2022-02-24 at 12 02 31 PM](https://user-images.githubusercontent.com/845363/155575829-37529ae3-eeb5-4cb6-bfb5-51ded5047f46.png)

2022-02-24 19:10 UTC, tpendragon approved these changes

2022-02-24 19:19 UTC, hackartisan requested changes
block on getting these translations back.

2022-02-24 19:41 UTC, eliotjordan approved these changes

2022-02-24 19:50 UTC, hackartisan approved these changes
Created https://github.com/geoblacklight/geoblacklight/issues/1200 to un-block merge of this ticket, since another 4.0 ticket depends on this getting merged.

2022-02-24 19:53 UTC, merged