add sidebar to map
geoblacklight/geoblacklight pull request #1466
Opened 2024-08-07 14:57 UTC by dnoneill

2024-08-09 15:02 UTC, ewlarson commented
I like this direction, if we can keep things manageable on smaller devices.

Also! Way back in the day we had talked about having a full feature table viewer. Something like this: https://developers.arcgis.com/javascript/latest/sample-code/widgets-featuretable-map/

![Screenshot 2024-08-09 at 10 00 43 AM](https://github.com/user-attachments/assets/199b2244-143b-4738-beb7-6be26b9659f8)

2024-08-09 20:38 UTC, srappel commented
@ewlarson this would actually be amazing for index maps, because it would allow someone to, for example, browse by title and sort columns as needed.

2024-08-09 20:45 UTC, ewlarson commented
Yeah, we talked about that at today's stand up. We can't do it for WMS items, which could potentially have 1M rows (HT / @kgjenkins), but for index maps this could work.

2025-01-29 21:57 UTC, thatbudakguy commented on app/assets/stylesheets/geoblacklight/modules/item.scss
> +    overflow: scroll;
```suggestion
    overflow: scroll;
    overscroll-behavior: contain;
```
I noticed that when scrolling in the sidebar, you could cause the underlying page to scroll if you scrolled past the end, which felt kind of strange. This seemed to fix it

2025-01-29 23:04 UTC, thatbudakguy requested changes

2025-01-29 23:04 UTC, thatbudakguy commented on app/components/geoblacklight/attribute_table_component.html.erb
> +    </button>
This and the `IndexMapInspectComponent` now seem to have a lot of shared code around this collapsible portion. Could we extract that as a wrapper component, and use Bootstrap's [built-in accordion](https://getbootstrap.com/docs/5.3/components/accordion/) with a single item? I tried this locally and it seemed to work and look OK; you get the icon and the open/close behavior "for free".

2025-01-29 23:04 UTC, thatbudakguy commented on app/components/geoblacklight/index_map_inspect_component.html.erb
> +<div id="<%= Settings.LEAFLET.SIDEBAR_ID || 'table-container' %>" data-sidebar="<%= Settings.LEAFLET.SIDEBAR_ID %>">
I think I'd rather have the simplicity/readability of a hardcoded/default sidebar ID than whatever this is allowing you to do. Judging from the javascript, if `SIDEBAR_ID` is set, we will find this element, look at its data attribute, and then use that to find another element...which is always itself? I'm not convinced the flexibility is necessary right now.

2025-01-29 23:06 UTC, thatbudakguy commented on app/components/geoblacklight/attribute_table_component.html.erb
> +    </button>
Locally, I tried a component like:
```erb
<div class="accordion" id="<%= @id %>">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        <%= @title %>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#<%= @id %>">
      <div class="accordion-body">
        <%= content %>
      </div>
    </div>
  </div>
</div>
```

So that you could then do:
```erb
<% render Geoblacklight::AccordionComponent.new(title:, id: 'index-map-accordion') do %>
  <div id="index-map-attributes" class="viewer-information">
    <em><%= t('geoblacklight.show.click_map') %></em>
  </div>
<% end %>
```

2025-07-28 21:32 UTC, dnoneill commented on app/components/geoblacklight/attribute_table_component.html.erb
> +    </button>
I am seeing something different when they are added to the map. No only does the icon not show up but the header keeps resizing when collapsed. Did you test it with the sidebar?
<img width="394" height="292" alt="Screenshot 2025-07-28 at 5 30 52 PM" src="https://github.com/user-attachments/assets/48661641-b92b-4bd6-ada8-8dec083a65fb" />
<img width="297" height="370" alt="Screenshot 2025-07-28 at 5 30 48 PM" src="https://github.com/user-attachments/assets/0dc44b44-e168-412f-bf7c-6e41a70cb280" />

2025-07-30 18:57 UTC, thatbudakguy commented
Everything seems to be working! Only thing I noticed is that when you have `SIDEBAR: false` there's no more border to the attribute table on the bottom, so it looks a little weird (imo):

<img width="1113" height="757" alt="Screenshot 2025-07-30 at 11 56 04" src="https://github.com/user-attachments/assets/2e517c3a-22d2-4bbd-86c6-fcce074b06b5" />

2025-07-30 20:20 UTC, thatbudakguy approved these changes
Works great! We should put a note somewhere (probably https://geoblacklight.org/docs/settings/) about how to enable it.

2026-05-27 17:09 UTC, merged