Bug fix - Build Docker builds with Vite asset pipeline
geoblacklight/geoblacklight pull request #1517
Opened 2024-08-15 16:38 UTC by ewlarson

Invoke the Vite asset pipeline.

2024-08-16 20:13 UTC, ewlarson commented on template.rb
> +generate "geoblacklight:assets:vite"
Forcing the vite generator here does resolved the assets.

2024-08-16 20:13 UTC, ewlarson commented on .github/workflows/build-demo-app.yml
> +        run: BRANCH=${{ env.BRANCH }} ASSET_PIPELINE=vite rails new build -m template.rb -a propshaft
Adding this env var here did propogate the value through the to docker build.

2024-08-16 20:43 UTC, ewlarson commented
Assets via Vite:

![Screenshot 2024-08-16 at 3 42 05 PM](https://github.com/user-attachments/assets/40a5f989-d92c-49f5-b4b2-8fb033233623)

2024-08-16 20:47 UTC, thatbudakguy requested changes
Vite is the default and shouldn't require any configuration:
https://github.com/geoblacklight/geoblacklight/blob/6776b5ac8c08c041733e76f7f3f4ce6a1d0dd71a/lib/generators/geoblacklight/assets_generator.rb#L7

Is something else messed up here? Is `ASSET_PIPELINE` somehow set to something in the docker container? You shouldn't need to set it at all in order for the vite generator to run. Maybe the `ENV.fetch` logic is somehow wrong?

2024-08-16 20:48 UTC, thatbudakguy commented
I wonder if the `class_option` should just default to `vite`, and then we should use `ENV["ASSET_PIPELINE"]` explicitly in the template.rb file?

You should never need to call the asset generator directly; `geoblacklight:install` should invoke it for you.

2024-08-16 20:59 UTC, ewlarson commented
> Is something else messed up here? Is ASSET_PIPELINE somehow set to something in the docker container? You shouldn't need to set it at all in order for the vite generator to run. Maybe the ENV.fetch logic is somehow wrong?

Yeah, your code _reads_ fine to me, but for whatever reason, the asset generator just doesn't run... This change is a bit heavy-handed, but fixes the current no-assets Docker builds.

2024-08-17 01:46 UTC, eliotjordan approved these changes

2024-08-17 02:44 UTC, eliotjordan commented
@ewlarson @thatbudakguy There were a few problems with the install and assets generators - primarily the assets were not generated outside if :test. I fixed that up and was able to get it working without running the assets generator directly in template.rb.

2024-08-17 02:45 UTC, eliotjordan approved these changes

2024-08-17 02:45 UTC, merged